---
- hosts: all
  sudo: yes
  gather_facts: yes
  roles:
    - role: base
    - role: aws-scripts
    - role: erase-ssh-keys
    -
      role: java
      java_packages:
        - oracle-java8-installer
        - oracle-java8-set-default
    - role: consul
    - role: userify
    -
      role: docker
      docker_version: 1.5.0
      docker_opts: --insecure-registry registry.connectedfleet.io
    - role: logstash
    -
      role: stackdriver
      stackdriver_api_key: X81H620HG3XG6KNI3EM7IU8W836U4AS5
