- src: git+git@github.com:PeopleNet/ansible-consul.git
  version: 1.0.0
  name: consul

- src: playlist.java
  name: java

- src: git+git@github.com:PeopleNet/ansible-userify.git
  version: 1.0.1
  name: userify

- src: git+git@github.com:PeopleNet/ansible-docker.git
  version: 1.0.3
  name: docker

- src: git+git@github.com:PeopleNet/ansible-logstash.git
  version: 1.0.4
  name: logstash
